### ISSUE TITLE
Docker container size

### ISSUE THREAD

**Issue by niel-lambrechts** [rofrano/vagrant-docker-image#4]
Hi John, Is it possible to provision a larger Vagrant docker container? The Vagrant notes on disk sizes (https://www.vagrantup.com/docs/disks/usage) seem to only apply to Virtual Box. I am using APFS on MacOS, and df showed that "overlay" on / (11G) was full during my build phase, so I need more temporary storage.

**Comment by rofrano** [comment]
@niel-lambrechts Sure. Do you know what I need to change in order to specify a larger container? If not, I will look it up and try and figure it out. :-)

**Comment by rofrano** [comment]
I'm not seeing any limitation. Docker Desktop on my Mac is using the default installation and the docker volume is set to 59.6GB and when I create a docker container I see all of that space as available to the container:

```bash
% docker run --rm -it rofrano/vagrant-provider:ubuntu bash
root@3189a0e5e91c:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G  1.9G   54G   4% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/vda1        59G  1.9G   54G   4% /etc/hosts
tmpfs           993M     0  993M   0% /proc/acpi
tmpfs           993M     0  993M   0% /sys/firmware
```

My `overlay` shows all 59G available. Is this not what you see?

**Comment by niel-lambrechts** [comment]
Hi John, yes mine was only 10GB for some reason. I migrated from an Intel Mac, so presumably something was inherited. I now experienced a Docker error when trying to set the container size (the daemon failed to start up), which led me to do a Docker reset - this seems to have done the trick as my container size is now 64GB.

Thanks for all the help!

**Comment by rofrano** [comment]
Awesome! Glad you figured it out. Enjoy! :-D
